services:
  frontend:
    build: frontend/.
    ports:
      - "8080:80"
    container_name: frontend
    restart: unless-stopped

  backend:
    build: backend/.
    ports:
      - "8000:8000"
    container_name: backend
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: backend-admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: backend-db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    container_name: timely-db
    restart: unless-stopped

volumes:
  db-data:
