services:
  frontend:
    build: frontend/.
    ports:
      - "5173:80"
    container_name: frontend
    restart: unless-stopped

  backend:
    build: backend/.
    ports:
      - "8000:8000"
    container_name: backend
    restart: unless-stopped
    env_file:
      - .env

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    container_name: timely-db
    restart: unless-stopped

volumes:
  db-data:
