# Generated by Django 5.2.1 on 2025-05-28 07:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_alter_category_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('energy_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('excited', 'Excited'), ('content', 'Content'), ('grateful', 'Grateful'), ('motivated', 'Motivated'), ('peaceful', 'Peaceful'), ('neutral', 'Neutral'), ('tired', 'Tired'), ('bored', 'Bored'), ('indifferent', 'Indifferent'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('stressed', 'Stressed'), ('overwhelmed', 'Overwhelmed'), ('angry', 'Angry'), ('lonely', 'Lonely'), ('frustrated', 'Frustrated'), ('fearful', 'Fearful'), ('guilty', 'Guilty')], max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
        ),
    ]
