# Generated by Django 5.2.1 on 2025-05-28 07:43

import categories.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(max_length=7, validators=[categories.validators.validate_hex_color]),
        ),
    ]
